// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Songify_FullStack.Data;

#nullable disable

namespace Songify_FullStack.Migrations
{
    [DbContext(typeof(SongifyContext))]
    [Migration("20230323055416_TestListenerLists")]
    partial class TestListenerLists
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Songify_FullStack.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Artist");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Contributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<int?>("EpisodeId")
                        .HasColumnType("int");

                    b.Property<int?>("PodcastId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SongId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("EpisodeId");

                    b.HasIndex("PodcastId");

                    b.HasIndex("SongId");

                    b.ToTable("Contributor");
                });

            modelBuilder.Entity("Songify_FullStack.Models.LibrarySong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("LibrarySong");
                });

            modelBuilder.Entity("Songify_FullStack.Models.ListenerList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ListenerList");
                });

            modelBuilder.Entity("Songify_FullStack.Models.ListenerListPodcasts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ListenerListId")
                        .HasColumnType("int");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ListenerListId");

                    b.HasIndex("PodcastId");

                    b.ToTable("ListenerListPodcasts");
                });

            modelBuilder.Entity("Songify_FullStack.Models.MediaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("int");

                    b.Property<string>("MediaItemType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("mediaItems");

                    b.HasDiscriminator<string>("MediaItemType").HasValue("MediaItem");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Songify_FullStack.Models.MediaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("mediaTypes");

                    b.HasDiscriminator<string>("MediaType").HasValue("MediaType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Songify_FullStack.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("Songify_FullStack.Models.PlaylistSong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ListenerListId")
                        .HasColumnType("int");

                    b.Property<int>("PlaylistId")
                        .HasColumnType("int");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeAdded")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ListenerListId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistSong");
                });

            modelBuilder.Entity("Songify_FullStack.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Episode", b =>
                {
                    b.HasBaseType("Songify_FullStack.Models.MediaItem");

                    b.Property<DateTime>("AirDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PodcastId")
                        .HasColumnType("int");

                    b.HasIndex("PodcastId");

                    b.HasDiscriminator().HasValue("Episode");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Song", b =>
                {
                    b.HasBaseType("Songify_FullStack.Models.MediaItem");

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.HasIndex("AlbumId");

                    b.HasDiscriminator().HasValue("Song");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Album", b =>
                {
                    b.HasBaseType("Songify_FullStack.Models.MediaType");

                    b.HasDiscriminator().HasValue("Album");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Podcast", b =>
                {
                    b.HasBaseType("Songify_FullStack.Models.MediaType");

                    b.HasDiscriminator().HasValue("Podcast");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Contributor", b =>
                {
                    b.HasOne("Songify_FullStack.Models.Artist", "Artist")
                        .WithMany("Contributors")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Songify_FullStack.Models.Episode", null)
                        .WithMany("Contributors")
                        .HasForeignKey("EpisodeId");

                    b.HasOne("Songify_FullStack.Models.Podcast", "Podcast")
                        .WithMany("Contributions")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Songify_FullStack.Models.Song", "Song")
                        .WithMany("Contributors")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");

                    b.Navigation("Podcast");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Songify_FullStack.Models.LibrarySong", b =>
                {
                    b.HasOne("Songify_FullStack.Models.Song", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Songify_FullStack.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Songify_FullStack.Models.ListenerList", b =>
                {
                    b.HasOne("Songify_FullStack.Models.User", "User")
                        .WithMany("ListenerLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Songify_FullStack.Models.ListenerListPodcasts", b =>
                {
                    b.HasOne("Songify_FullStack.Models.ListenerList", "ListenerList")
                        .WithMany()
                        .HasForeignKey("ListenerListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Songify_FullStack.Models.Podcast", "Podcast")
                        .WithMany("ListenerListPodcasts")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ListenerList");

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Playlist", b =>
                {
                    b.HasOne("Songify_FullStack.Models.User", "User")
                        .WithMany("Playlists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Songify_FullStack.Models.PlaylistSong", b =>
                {
                    b.HasOne("Songify_FullStack.Models.ListenerList", null)
                        .WithMany("ListenerListPodcasts")
                        .HasForeignKey("ListenerListId");

                    b.HasOne("Songify_FullStack.Models.Playlist", "Playlist")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Songify_FullStack.Models.Song", "Song")
                        .WithMany("PlaylistSongs")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Episode", b =>
                {
                    b.HasOne("Songify_FullStack.Models.Podcast", "Podcast")
                        .WithMany("Episodes")
                        .HasForeignKey("PodcastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Podcast");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Song", b =>
                {
                    b.HasOne("Songify_FullStack.Models.Album", "Album")
                        .WithMany("Songs")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Artist", b =>
                {
                    b.Navigation("Contributors");
                });

            modelBuilder.Entity("Songify_FullStack.Models.ListenerList", b =>
                {
                    b.Navigation("ListenerListPodcasts");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Playlist", b =>
                {
                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("Songify_FullStack.Models.User", b =>
                {
                    b.Navigation("ListenerLists");

                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Episode", b =>
                {
                    b.Navigation("Contributors");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Song", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("PlaylistSongs");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Album", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("Songify_FullStack.Models.Podcast", b =>
                {
                    b.Navigation("Contributions");

                    b.Navigation("Episodes");

                    b.Navigation("ListenerListPodcasts");
                });
#pragma warning restore 612, 618
        }
    }
}
